# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('document_url', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
